# Generated by Django 4.2.6 on 2023-10-28 22:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sducraft.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string', models.CharField(default=sducraft.models.getRandomString, max_length=32)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('front_end_address', models.CharField(blank=True, default='nowhere', max_length=64, null=True)),
                ('file', models.FileField(upload_to=sducraft.models.custom_upload_path)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string', models.CharField(default=sducraft.models.getRandomString, max_length=32)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=sducraft.models.custom_upload_path)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('version', models.CharField(blank=True, max_length=32, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string', models.CharField(default=sducraft.models.getRandomString, max_length=32)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('front_end_address', models.CharField(blank=True, default='nowhere', max_length=64, null=True)),
                ('file', models.FileField(upload_to=sducraft.models.custom_upload_path)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('rank', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string', models.CharField(default=sducraft.models.getRandomString, max_length=32)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('front_end_address', models.CharField(blank=True, default='nowhere', max_length=64, null=True)),
                ('file', models.FileField(upload_to=sducraft.models.custom_upload_path)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('valid', models.IntegerField(choices=[(0, '无效'), (1, '有效'), (2, '置顶'), (3, '重要')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProxyServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('version', models.CharField(max_length=32)),
                ('host', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('intro', models.TextField()),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(blank=True, max_length=16, null=True)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(blank=True, max_length=16, null=True)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('rank', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='VMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string', models.CharField(default=sducraft.models.getRandomString, max_length=32)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=sducraft.models.custom_upload_path)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('campus', models.CharField(blank=True, max_length=16, null=True)),
                ('school', models.CharField(blank=True, max_length=16, null=True)),
                ('grade', models.IntegerField(default=1901)),
                ('major', models.CharField(blank=True, max_length=16, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sducraft.vgroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='vgroup',
            name='team_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sducraft.vteam'),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('mode', models.CharField(choices=[('survival', 'survival'), ('creative', 'creative'), ('adventure', 'adventure'), ('spectator', 'spectator'), ('hardcore', 'hardcore')], default='survival', max_length=16)),
                ('version', models.CharField(max_length=32)),
                ('host', models.CharField(max_length=32)),
                ('port', models.IntegerField()),
                ('bridge_name', models.CharField(max_length=16)),
                ('author', models.CharField(max_length=32)),
                ('init_date', models.DateTimeField()),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('intro', models.TextField()),
                ('rank', models.IntegerField(default=0)),
                ('proxyServer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sducraft.proxyserver')),
            ],
        ),
        migrations.CreateModel(
            name='ImageSetForServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string', models.CharField(default=sducraft.models.getRandomString, max_length=32)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=sducraft.models.custom_upload_path)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sducraft.server')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageSetForProxyServer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string', models.CharField(default=sducraft.models.getRandomString, max_length=32)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=sducraft.models.custom_upload_path)),
                ('proxyServer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sducraft.proxyserver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('level', models.IntegerField(choices=[(0, '一般'), (1, '重要')], default=0)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField(blank=True, null=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sducraft.history')),
            ],
        ),
        migrations.CreateModel(
            name='FileSetForDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string', models.CharField(default=sducraft.models.getRandomString, max_length=32)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=sducraft.models.custom_upload_path)),
                ('OS', models.CharField(choices=[('Windows', 'Windows'), ('Mac', 'Mac'), ('Linux', 'Linux')], default='Windows', max_length=16)),
                ('size', models.FloatField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('download', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sducraft.download')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
