# Generated by Django 4.2.6 on 2023-11-09 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sducraft', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vgroup',
            name='group_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='vteam',
            name='team_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
