# Generated by Django 4.2.6 on 2023-11-09 02:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sducraft.models


class Migration(migrations.Migration):

    dependencies = [
        ('sducraft', '0002_alter_vgroup_group_name_alter_vteam_team_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSetForHistoryNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string', models.CharField(default=sducraft.models.getRandomString, max_length=32)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=sducraft.models.custom_upload_path)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sducraft.historynode')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
