# Generated by Django 4.2.6 on 2023-11-09 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sducraft', '0003_imagesetforhistorynode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagesetforhistorynode',
            old_name='server',
            new_name='historynode',
        ),
    ]
