# Generated by Django 4.2.6 on 2023-11-09 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sducraft', '0005_imagesetforhistorynode_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='author',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='bridge_name',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='port',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
