# Generated by Django 4.2.6 on 2023-11-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sducraft', '0006_alter_server_author_alter_server_bridge_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='invalid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='server',
            name='host',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
