# Generated by Django 4.2.6 on 2023-11-10 04:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import sducraft.models


class Migration(migrations.Migration):

    dependencies = [
        ('sducraft', '0007_notice_invalid_date_alter_server_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string', models.CharField(default=sducraft.models.getRandomString, max_length=32)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('front_end_address', models.CharField(blank=True, default='nowhere', max_length=64, null=True)),
                ('file', models.FileField(upload_to=sducraft.models.custom_upload_path)),
                ('title', models.CharField(blank=True, max_length=32, null=True)),
                ('author', models.CharField(blank=True, max_length=32, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('rank', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageSetForActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('random_string', models.CharField(default=sducraft.models.getRandomString, max_length=32)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to=sducraft.models.custom_upload_path)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sducraft.activity')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
