# Generated by Django 4.2.6 on 2023-11-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sducraft', '0008_activity_imagesetforactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='wordCount',
            field=models.IntegerField(default=0),
        ),
    ]
