# Generated by Django 4.2.6 on 2023-11-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sducraft', '0009_activity_wordcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='author',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
